# Generated by Django 5.2.5 on 2025-11-08 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_plan_alter_empresa_plan'),
        ('users', '0002_alter_role_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='is_active',
            new_name='esta_activo',
        ),
        migrations.AddField(
            model_name='permission',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.empresa'),
        ),
        migrations.AddField(
            model_name='role',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.empresa'),
        ),
        migrations.AddField(
            model_name='role',
            name='esta_activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='tenants.empresa'),
        ),
        migrations.AddField(
            model_name='user',
            name='esta_activo',
            field=models.BooleanField(default=True),
        ),
    ]
