# Generated by Django 5.2.5 on 2025-11-11 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_plan_alter_empresa_plan'),
        ('users', '0004_user_onesignal_player_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('empresa', 'name')},
        ),
    ]
