# Generated by Django 5.2.5 on 2025-11-06 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='venta',
            name='numero_nota',
            field=models.CharField(default='TEMP-NOTA', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='metodo_pago',
            name='proveedor',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterModelTable(
            name='detalleventa',
            table='detalle_venta',
        ),
    ]
