# Generated by Django 5.2.5 on 2025-11-06 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_detalleventa_subtotal_venta_numero_nota_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='numero_nota',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
