# Generated by Django 5.2.5 on 2025-11-11 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sucursales', '0006_departamento_empresa_alter_departamento_nombre_and_more'),
        ('ventas', '0004_alter_pago_options_alter_venta_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='canal',
            field=models.CharField(blank=True, choices=[('POS', 'Punto de Venta'), ('WEB', 'Tienda en Línea'), ('OTRO', 'Otro')], default='POS', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='sucursal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='sucursales.sucursal'),
        ),
    ]
