# Generated by Django 5.2.5 on 2025-11-06 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('nit', models.CharField(max_length=50, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('plan', models.CharField(default='BASIC', max_length=50)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='empresas/')),
                ('esta_activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'Empresa',
            },
        ),
    ]
