# Generated by Django 5.2.5 on 2025-11-08 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('max_usuarios', models.PositiveBigIntegerField(blank=True, null=True)),
                ('max_productos', models.PositiveIntegerField(blank=True, null=True)),
                ('max_ventas_mensuales', models.PositiveIntegerField(blank=True, null=True)),
                ('almacenamiento_gb', models.PositiveIntegerField(default=1)),
                ('precio_mensual', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('permite_reportes_ia', models.BooleanField(default=False)),
                ('permite_exportar_excel', models.BooleanField(default=False)),
                ('permite_notificaciones_push', models.BooleanField(default=False)),
                ('soporte_prioritario', models.BooleanField(default=False)),
                ('esta_activo', models.BooleanField(default=True)),
                ('prediccion_ventas', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'plan',
            },
        ),
        migrations.AlterField(
            model_name='empresa',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.plan'),
        ),
    ]
