# Generated by Django 5.2.5 on 2025-11-01 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_surcursal_descuento_sucursal'),
        ('sucursales', '0002_departamento_direccion_alter_sucursal_direccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockSucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.PositiveBigIntegerField(default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.producto')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sucursales.sucursal')),
            ],
            options={
                'verbose_name': 'Stock en Sucursal',
                'verbose_name_plural': 'Stock en Sucursales',
                'unique_together': {('producto', 'sucursal')},
            },
        ),
    ]
