# Generated by Django 5.2.5 on 2025-11-08 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sucursales', '0003_stocksucursal'),
        ('tenants', '0002_plan_alter_empresa_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='direccion',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direcciones', to='tenants.empresa'),
        ),
        migrations.AddField(
            model_name='stocksucursal',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.empresa'),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.empresa'),
        ),
    ]
