# Generated by Django 5.2.5 on 2025-11-08 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sucursales', '0004_direccion_empresa_stocksucursal_empresa_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='direccion',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direcciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='pais',
            field=models.CharField(default='Bolivia', max_length=50),
        ),
    ]
