# Generated by Django 5.2.5 on 2025-11-08 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_categoria_nombre_alter_producto_sku_and_more'),
        ('sucursales', '0005_direccion_cliente_alter_direccion_pais'),
        ('tenants', '0002_plan_alter_empresa_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departamentos', to='tenants.empresa'),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='departamento',
            unique_together={('empresa', 'nombre')},
        ),
        migrations.AlterUniqueTogether(
            name='stocksucursal',
            unique_together={('empresa', 'producto', 'sucursal')},
        ),
        migrations.AlterUniqueTogether(
            name='sucursal',
            unique_together={('empresa', 'nombre')},
        ),
    ]
