# Generated by Django 5.2.5 on 2025-10-25 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='descuento',
            old_name='surcursal',
            new_name='sucursal',
        ),
    ]
