# Generated by Django 5.2.5 on 2025-11-08 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_campania_empresa_categoria_empresa_descuento_empresa_and_more'),
        ('sucursales', '0005_direccion_cliente_alter_direccion_pais'),
        ('tenants', '0002_plan_alter_empresa_plan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campania',
            options={'verbose_name': 'Campaña', 'verbose_name_plural': 'Campañas'},
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'Categoría (Nivel 1)', 'verbose_name_plural': 'Categorías (Nivel 1)'},
        ),
        migrations.AlterModelOptions(
            name='descuento',
            options={'verbose_name': 'Descuento', 'verbose_name_plural': 'Descuentos'},
        ),
        migrations.AlterModelOptions(
            name='detalleproducto',
            options={'verbose_name': 'Ficha Técnica (Detalle)', 'verbose_name_plural': 'Fichas Técnicas (Detalles)'},
        ),
        migrations.AlterModelOptions(
            name='imagenproducto',
            options={'verbose_name': 'Imagen de Producto', 'verbose_name_plural': 'Imágenes de Producto'},
        ),
        migrations.AlterModelOptions(
            name='marca',
            options={'verbose_name': 'Marca', 'verbose_name_plural': 'Marcas'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'verbose_name': 'Producto (SKU)', 'verbose_name_plural': 'Productos (SKUs)'},
        ),
        migrations.RemoveField(
            model_name='detalleproducto',
            name='color',
        ),
        migrations.RemoveField(
            model_name='detalleproducto',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='detalleproducto',
            name='precio_venta',
        ),
        migrations.AddField(
            model_name='detalleproducto',
            name='aire_frio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='detalleproducto',
            name='largo_cable',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='detalleproducto',
            name='potencia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='detalleproducto',
            name='tecnologias',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='detalleproducto',
            name='velocidades',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='detalleproducto',
            name='voltaje',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='marca',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marca',
            name='pais_origen',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='marca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='products.marca'),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_venta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='producto',
            name='sku',
            field=models.CharField(blank=True, help_text='Código único de producto (SKU) para gestión e inventario', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='campania',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campanias', to='tenants.empresa'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='tenants.empresa'),
        ),
        migrations.AlterField(
            model_name='descuento',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='descuentos', to='tenants.empresa'),
        ),
        migrations.AlterField(
            model_name='detalleproducto',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalles_producto', to='tenants.empresa'),
        ),
        migrations.AlterField(
            model_name='imagenproducto',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imagenes_producto', to='tenants.empresa'),
        ),
        migrations.AlterField(
            model_name='marca',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marcas', to='tenants.empresa'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, help_text='El párrafo de marketing (Información Adicional)', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='descuento',
            unique_together={('empresa', 'producto', 'sucursal')},
        ),
        migrations.CreateModel(
            name='SubCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('esta_activo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='products.categoria')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias_empresa', to='tenants.empresa')),
            ],
            options={
                'verbose_name': 'Subcategoría (Nivel 2)',
                'verbose_name_plural': 'Subcategorías (Nivel 2)',
                'db_table': 'subcategoria',
                'ordering': ['categoria__nombre', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='subcategoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='products.subcategoria'),
        ),
        migrations.DeleteModel(
            name='ProductoCategoria',
        ),
    ]
