# Generated by Django 5.2.5 on 2025-11-08 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_campania_options_alter_categoria_options_and_more'),
        ('tenants', '0002_plan_alter_empresa_plan'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='marca',
            unique_together={('empresa', 'nombre')},
        ),
    ]
