# Generated by Django 5.2.5 on 2025-11-08 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_marca_nombre'),
        ('tenants', '0002_plan_alter_empresa_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='producto',
            name='sku',
            field=models.CharField(blank=True, help_text='Código único de producto (SKU) para gestión e inventario', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subcategoria',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='campania',
            unique_together={('empresa', 'nombre')},
        ),
        migrations.AlterUniqueTogether(
            name='categoria',
            unique_together={('empresa', 'nombre')},
        ),
        migrations.AlterUniqueTogether(
            name='producto',
            unique_together={('empresa', 'sku')},
        ),
        migrations.AlterUniqueTogether(
            name='subcategoria',
            unique_together={('empresa', 'nombre')},
        ),
    ]
